### ISSUE TITLE
Stopped working for SS 4.3

### ISSUE THREAD

**Issue by lohe** [pchschulz/silverstripe-gallery#1]
Hei.

It stopped working after update to SS 4.3 due to fact the core (think it was core) was also updated from 1.1 to higher version.
**Edit** - adding install log!
[gallery.install.log](https://github.com/pchschulz/silverstripe-gallery/files/2807042/gallery.install.log)

**Comment by pchschulz** [comment]
Thanks for reporting.
This is fixed in the newest release.
The "recipe-core" package was removed from the dependencies and replaced by the single packages needed.
Sorry for the long wait.
